//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenTalkingServiceClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://vk.com/nuadolos", ConfigurationName="ServiceReference1.BenTalking")]
    public interface BenTalking {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://vk.com/nuadolos/BenTalking/BenAnswerToQuestion", ReplyAction="https://vk.com/nuadolos/BenTalking/BenAnswerToQuestionResponse")]
        string BenAnswerToQuestion(string userQuestion);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://vk.com/nuadolos/BenTalking/BenAnswerToQuestion", ReplyAction="https://vk.com/nuadolos/BenTalking/BenAnswerToQuestionResponse")]
        System.Threading.Tasks.Task<string> BenAnswerToQuestionAsync(string userQuestion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BenTalkingChannel : BenTalkingServiceClient.ServiceReference1.BenTalking, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BenTalkingClient : System.ServiceModel.ClientBase<BenTalkingServiceClient.ServiceReference1.BenTalking>, BenTalkingServiceClient.ServiceReference1.BenTalking {
        
        public BenTalkingClient() {
        }
        
        public BenTalkingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BenTalkingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BenTalkingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BenTalkingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string BenAnswerToQuestion(string userQuestion) {
            return base.Channel.BenAnswerToQuestion(userQuestion);
        }
        
        public System.Threading.Tasks.Task<string> BenAnswerToQuestionAsync(string userQuestion) {
            return base.Channel.BenAnswerToQuestionAsync(userQuestion);
        }
    }
}
